// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYN2zE_Snh4SXtlloqVc4okw-9wtiPME8',
    appId: '1:769279018698:web:69cf41b94b5625af2e9633',
    messagingSenderId: '769279018698',
    projectId: 'urbanartist-191cf',
    authDomain: 'urbanartist-191cf.firebaseapp.com',
    storageBucket: 'urbanartist-191cf.appspot.com',
    measurementId: 'G-8ZP7CVQ9EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbYKIKtQkm11csz45nVfFyHsVzbYt5Reo',
    appId: '1:769279018698:android:37148335986d4cde2e9633',
    messagingSenderId: '769279018698',
    projectId: 'urbanartist-191cf',
    storageBucket: 'urbanartist-191cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqRGYN5GtEsxgKthFxHlyoZnSyYVXgni8',
    appId: '1:769279018698:ios:ea80ff4f15314f7a2e9633',
    messagingSenderId: '769279018698',
    projectId: 'urbanartist-191cf',
    storageBucket: 'urbanartist-191cf.appspot.com',
    iosClientId: '769279018698-kon96e72cchksbfains200k42ccurjmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbanArtist',
  );
}
